GigHubSite/GigHub/urls.py
from django.urls import path
from . import views


app_name = "GigHub"

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login, name="login"),
    path('register/',views.register, name="register"),
    path('privacy_policy/',views.privacy_policy, name="privacy_policy"),
    path('forgot/',views.forgot, name="forgot"),
    path('verify/',views.verify, name="verify"),
    path('changePass/',views.changePass, name="changePass"),
    path('logout/', views.logout, name="logout"),
    path('changeProfile/', views.Profilechange, name="changeProfile"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('addSkills/', views.addSkills, name="addSkills"),
    path('addCollege/',views.addCollege, name="addCollege"),
    path('addCompany/',views.addCompany, name="addCompany"),
    path('addPosting/',views.addJobPosting, name="addJobPosting"),
    path('register_education/', views.register_education, name="register_education"),
    path('register_skills/', views.register_skills, name="register_skills"),
    path('register_moreInfo/', views.register_moreInfo, name="register_moreInfo"),
    path('getMajors/<str:degreeName>/', views.getMajors, name="getMajors"),
    path('disabled/',views.disabled,name="disabled")
]

GigHubSite/GigHubSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GigHub.urls')),
    path('user/',include('jobSeeker.urls')),
    path('provider/',include('jobProvider.urls')),
    path('administrator/',include('gigAdmin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GigHubSite/jobSeeker/urls.py
from django.urls import path
from . import views

app_name="jobSeeker"

urlpatterns = [
    path('settings/',views.profileSettings,name="userSettings"),
    path('education/',views.profileEducation, name="profileEducation"),
    path('awards/',views.addAward, name="profileAward"),
    path('certificates/',views.addCertis, name="profileCerties"),
    path('account/email/',views.accountEmail, name="accountEmail"),
    path('account/password/',views.accountPassword,name="accountPassword"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('job/',views.job,name="job"),
    path('searchResult/',views.searchResult,name="searchResult"),
    path('employment/',views.addEmployment,name="employment"),
    path('getMessage/<int:appID>/',views.getMessage,name="getMessage"),
    path('sendMessage/',views.sendMessage,name="sendMessage"),
    path('deleteEducation/<int:educID>/',views.deleteEducation,name="deleteEducation"),
    path('deleteWork/<int:workID>/',views.deleteWork,name="deleteWork")

]

GigHubSite/jobSeeker/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from GigHub.models import Profile, collegeTaken, Institution, Majors, Degrees, JobPostings, Awards, Certificates, JobApplication, EmploymentHistory, Room, Activities,Message
from GigHub import utils
from django.contrib.auth.models import User
from datetime import date, datetime
from django.contrib.auth.hashers import check_password
from django.db.models import Count, Q

import json
# Create your views here.


def searchResult(request):
    template="searchResult.html"
    profile = Profile.objects.get(userID=request.user)
    if request.method == "GET":


        jobs = JobApplication.objects.filter(applicantID=profile)



        return render(request, template,{'user':profile,'jobs':jobs})
    
def profileSettings(request):
    template = 'userSettings.html'
    if request.method == "GET":
        
        profile=Profile.objects.get(userID=request.user)
       
        colleges_queryset = collegeTaken.objects.filter(userID=profile)
        awards_queryset = Awards.objects.filter(user=profile)
        college_data_list = []
        certificate_data_list = []
        certificates_queryset = Certificates.objects.filter(user=profile)
        ins = Institution.objects.all()
        deg = Degrees.objects.all()


        awards_data_list = []

        employment_queryset = EmploymentHistory.objects.filter(user=profile)
        employment_data_list = []

        for employment in employment_queryset:
            employment_data = {
                'id':employment.id,
                'name':employment.companyName,
                'position':employment.position,
                'start':employment.date_started.strftime('%B %Y'),
                'end':employment.date_ended.strftime('%B %Y') if employment.date_ended is not None else 'Present',
                'duties':employment.getDuties()
            }

            employment_data_list.append(employment_data)
        
        for college in colleges_queryset:
            institutions = [institution.name for institution in college.institution.all()]
            degrees = [degree.name for degree in college.degree.all()]
            majors = [major.name for major in college.major.all()]

            college_data = {
                'id':college.id,
                'institutions': institutions,
                'degrees': degrees,
                'majors': majors,
                'award':college.award if college.award is not None else '',
                'yearGraduated': college.yearGraduated,
            }

            college_data_list.append(college_data)

        for award in awards_queryset:

            award_data = {
                'title':award.title,
                'from':award.awardForm,
                'date':award.date
            }

            awards_data_list.append(award_data)

        for certiifcate in certificates_queryset:

            certiifcate_data = {
                'title':certiifcate.title,
                'from':certiifcate.certificateForm,
                'date':certiifcate.date
            }

            certificate_data_list.append(certiifcate_data)


        
        

        bdate = profile.birthDate
        today = date.today()
        age = today.year - bdate.year - ((today.month, today.day) < (bdate.month, bdate.day))
        return render(request, template, {'employment':employment_data_list,'certis':certificate_data_list,'awards':awards_data_list,'user':profile, 'age':age, 'statuses':profile.STATUS_CHOICES, 'pageName':'profileSettings', 'pagePart': 1, 'colleges':college_data_list, 'degrees':deg,'insitutions':ins})
    elif request.method == "POST":
        
        profile = Profile.objects.get(userID=request.user)
        
        profile.fName = request.POST['fName']
        profile.lName = request.POST['lName']
        profile.mName = request.POST['mName']
        profile.suffix = request.POST['suffix']
        profile.civilStatus = request.POST['status']
        profile.sex = request.POST['sex']
        profile.birthDate = request.POST['birthday']
        profile.baranggay = request.POST['barangay']
        profile.city = request.POST['city']
        profile.province = request.POST['province']
        if request.FILES.get('profileImg') is not None:
            profile.image = request.FILES.get('profileImg')

        profile.save()
        
        profile=Profile.objects.get(userID=request.user)
        certificates_queryset = Certificates.objects.filter(user=profile)
        colleges_queryset = collegeTaken.objects.filter(userID=profile)
        
        awards_queryset = Awards.objects.filter(user=profile)

        certificate_data_list = []
        awards_data_list = []
        ins = Institution.objects.all()
        deg = Degrees.objects.all()


        employment_queryset = EmploymentHistory.objects.filter(user=profile)
        employment_data_list = []

        for employment in employment_queryset:
            employment_data = {
                'id':employment.id,
                'name':employment.companyName,
                'position':employment.position,
                'start':employment.date_started.strftime('%B %Y'),
                'end':employment.date_ended.strftime('%B %Y') if employment.date_ended is not None else 'Present',
                'duties':employment.getDuties()
            }

            employment_data_list.append(employment_data)

        college_data_list = []
        for college in colleges_queryset:
            institutions = [institution.name for institution in college.institution.all()]
            degrees = [degree.name for degree in college.degree.all()]
            majors = [major.name for major in college.major.all()]

            

            college_data = {
                'id':college.id,
                'institutions': institutions,
                'degrees': degrees,
                'majors': majors,
                'award':college.award if college.award is not None else '',
                'yearGraduated': college.yearGraduated,
            }

            college_data_list.append(college_data)

        for award in awards_queryset:

            award_data = {
                'title':award.title,
                'from':award.awardForm,
                'date':award.date
            }

            awards_data_list.append(award_data)

        for certiifcate in certificates_queryset:

            certiifcate_data = {
                'title':certiifcate.title,
                'from':certiifcate.certificateForm,
                'date':certiifcate.date
            }

            certificate_data_list.append(certiifcate_data)
        
        

        bdate = profile.birthDate
        today = date.today()
        age = today.year - bdate.year - ((today.month, today.day) < (bdate.month, bdate.day))
        return render(request, template, {'employment':employment_data_list,'certis':certificate_data_list,'awards':awards_data_list,'user':profile, 'age':age, 'statuses':profile.STATUS_CHOICES, 'pageName':'profileSettings', 'prompt':'Profile has been saved', 'pagePart': 1, 'colleges':college_data_list, 'degrees':deg,'insitutions':ins})
    

def profileEducation(request):
    #guest = utils.checkAuth(request)
    #if guest != True:
    #    return redirect(f"{guest}")
    
    profile = Profile.objects.get(userID=request.user)
    institution_name = request.POST['uni']
    degree_name = request.POST['deg']
    major_name = request.POST['maj']
    date_string = request.POST['graduated']
    award = request.POST['award']
    year = date_string

    ins, created = Institution.objects.get_or_create(name__iexact=institution_name)
    if created or not ins.name:
        ins.name = institution_name
        ins.save()
    deg, createds = Degrees.objects.get_or_create(name__iexact=degree_name)
    if createds or not deg.name:
        deg.name = degree_name
        deg.save()

    if major_name != "":
        maj, createdss = Majors.objects.get_or_create(degree=deg, name__iexact=major_name)
        if createdss or not maj.name:
            maj.name = major_name
            maj.save()
   
    college_taken_instance = collegeTaken.objects.create(userID=profile, yearGraduated=year, award=award)
    college_taken_instance.institution.add(ins)
    college_taken_instance.degree.add(deg)
    if major_name != "":
        college_taken_instance.major.add(maj)
    college_taken_instance.save()

    return JsonResponse({'message':'Data has been saved','data':[institution_name,degree_name,major_name,year,award]})


def accountEmail(request):
    email = request.POST['email']
    password = request.POST['currentPassword']
    user = User.objects.get(id=request.user.id)
   
    passwordCheck = check_password(password, request.user.password)

    if passwordCheck:
        #user.set_password(password)
        user.username = email
        user.save()
        return JsonResponse({'status':True,'message':'Email has been changed'})

    return JsonResponse({'status':False,'message':'Inserted password is wrong'})

def accountPassword(request):
    oldPass = request.POST['currentpassword']
    newPass = request.POST['newpassword']
    user = User.objects.get(id=request.user.id)

    passwordCheck = check_password(oldPass, user.password)

    if passwordCheck:
        user.set_password(newPass)
        user.save()
        return JsonResponse({'status':True,'message':'Password has been changed'})
    
    return JsonResponse({'status':False,'message':'Your inserted password is wrong'})
    
    
def dashboard(request):
    template ="dashboard.html"
    if request.method == "GET":
        profile=Profile.objects.get(userID=request.user)
        acts = Activities.objects.filter(viewer=profile).order_by('-dateandtime')
        apps = len(JobApplication.objects.filter(applicantID=profile))
        pending = len(JobApplication.objects.filter(applicantID=profile,applicationStatus="applied"))

GigHubSite/jobSeeker/templates/partials/navbar.html
<div class="navbar w-auto d-flex align-items-center justify-content-between">
    <div class="leftNavBar w-auto d-flex align-items-center">
        <i class="fa-solid fa-bars" onclick="toggleSidebar(this)"></i>
        <div class="input-group">
            <input type="text" class="form-control custom-focus-style" placeholder="Search"
                aria-label="Username" aria-describedby="basic-addon1">
            <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-magnifying-glass"></i></span>
        </div>
    </div>
    <div class="rightNavbar w-auto h-100 d-flex align-items-center">
        <div class="notificationsContainer">
            <i class="fa-regular fa-bell"></i>
        </div>
        <div class="infoContainer d-flex align-items-center">
            <div class="imgLogin">
                <img src="{{ user.image.url }}" alt="">
            </div>
            <div class="greetings">
                <span class="greet">Good Day!</span>
                <div class="nameLogin">{{user.fName}} {{user.lName}}</div>
            </div>
        </div>
    </div>
</div>

GigHubSite/jobSeeker/templates/partials/sidebar.html
<div class="sideBar">
    <div class="imgGroupSidebar">
        <img src="{{ '/media/site/logo.png' }}" alt="">
        <img src="{{ '/media/site/logoText.png' }}" alt="" id="hiddenIMG">
    </div>
    <nav>
        <ul>
            <li class="" style="display: none;">
                <a href="/Admin/Dashboard.html">
                    <iconify-icon icon="ic:round-dashboard"></iconify-icon>
                    <span class="links">Dashboard</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Dashboard1.html">
                    <iconify-icon icon="ic:round-dashboard"></iconify-icon>
                    <span class="links">Dashboard Employer</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Profile.html" style="display: none;">
                    <iconify-icon icon="iconamoon:profile-circle-fill"></iconify-icon>
                    <span class="links">Profile</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Profile1.html">
                    <iconify-icon icon="iconamoon:profile-circle-fill"></iconify-icon>
                    <span class="links">Profile Employer</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Work.html">
                    <iconify-icon icon="solar:case-bold"></iconify-icon>
                    <span class="links">Work</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Company.html">
                    <iconify-icon icon="solar:case-bold"></iconify-icon>
                    <span class="links">Company</span>
                </a>
            </li>
            <li class="">
                <a href="/Admin/Job.html">
                    <i class="fa-solid fa-user-tie"></i>
                    <span class="links">Job</span>  
                </a>
            </li>
            <li class="">
                <a href="/Admin/Job1.html">
                    <i class="fa-solid fa-user-tie"></i>
                    <span class="links">Job</span>
                </a>
            </li>
            <li class="">
                <a href="/logout/">
                    <iconify-icon icon="basil:logout-solid"></iconify-icon>
                    <span class="links">Logout</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

GigHubSite/jobSeeker/templates/partials/template.html
<sidebar
  class="shadow d-flex flex-column align-items-center justify-content-between py-3 gap-3">
  <div class="logo">
    <img src="{{ '/media/site/logo.png' }}" alt="logo" />
    <img src="{{ '/media/site/logoText.png' }}" />
  </div>

  <div class="d-flex flex-column flex-grow-1 justify-content-between">
    <div class="tabs_list d-flex flex-column">
      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2 {% if pageName == 'dashBoard'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobSeeker:dashboard' %}`">
        <iconify-icon icon="ic:round-dashboard"></iconify-icon>
        <span>Dashboard</span>
      </div>

      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2 {% if pageName == 'profileSettings'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobSeeker:userSettings'%}`">
        <iconify-icon icon="iconamoon:profile-circle-fill"></iconify-icon>
        <span>Profile</span>
      </div>

      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2 {% if pageName == 'job'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobSeeker:job'%}`">
        <iconify-icon icon="gg:feed"></iconify-icon>
        <span>Job Postings</span>
      </div>

      <div class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2"
        onclick="window.location.href = `{% url 'jobSeeker:searchResult' %}`">
        <i class="fa-solid fa-user-tie"></i>
        <span>Job Applications</span>
      </div>
    </div>

    <div
      onclick="logout()"
      class="logout tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2">
      <iconify-icon icon="basil:logout-solid"></iconify-icon>
      <span>Logout</span>
    </div>
  </div>
</sidebar>
<header class="px-3 d-flex align-items-center gap-2 justify-content-between">
  <div class="left d-flex align-items-center gap-2">
    <iconify-icon icon="ci:hamburger-md" class="burger"></iconify-icon>
  </div>
  <div class="right d-flex align-items-center gap-2">
    
    <img
      src="{{ user.image.url }}"
      alt="my_profile"
      class="rounded-circle shadow-sm" />
    <div class="greetings fw-bold lh-sm">
      Good Day!
      <br />
      <span>{{user.fName}} {{user.lName}}</span>
    </div>
  </div>
</header>
<script>
  function logout() {
    Swal.fire({
      text: "Are you sure?",
      icon: "question",
      showCancelButton: true,
      confirmButtonText: "Yes",
    }).then((result) => {
      if (result.isConfirmed) {
        window.location.href = "/logout/";
      }
    });
  }
</script>