GigHubSite/GigHub/urls.py
from django.urls import path
from . import views


app_name = "GigHub"

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login, name="login"),
    path('register/',views.register, name="register"),
    path('privacy_policy/',views.privacy_policy, name="privacy_policy"),
    path('forgot/',views.forgot, name="forgot"),
    path('verify/',views.verify, name="verify"),
    path('changePass/',views.changePass, name="changePass"),
    path('logout/', views.logout, name="logout"),
    path('changeProfile/', views.Profilechange, name="changeProfile"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('addSkills/', views.addSkills, name="addSkills"),
    path('addCollege/',views.addCollege, name="addCollege"),
    path('addCompany/',views.addCompany, name="addCompany"),
    path('addPosting/',views.addJobPosting, name="addJobPosting"),
    path('register_education/', views.register_education, name="register_education"),
    path('register_skills/', views.register_skills, name="register_skills"),
    path('register_moreInfo/', views.register_moreInfo, name="register_moreInfo"),
    path('getMajors/<str:degreeName>/', views.getMajors, name="getMajors"),
    path('disabled/',views.disabled,name="disabled")
]

GigHubSite/GigHubSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GigHub.urls')),
    path('user/',include('jobSeeker.urls')),
    path('provider/',include('jobProvider.urls')),
    path('administrator/',include('gigAdmin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GigHubSite/jobSeeker/urls.py
from django.urls import path
from . import views

app_name="jobSeeker"

urlpatterns = [
    path('settings/',views.profileSettings,name="userSettings"),
    path('education/',views.profileEducation, name="profileEducation"),
    path('awards/',views.addAward, name="profileAward"),
    path('certificates/',views.addCertis, name="profileCerties"),
    path('account/email/',views.accountEmail, name="accountEmail"),
    path('account/password/',views.accountPassword,name="accountPassword"),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('job/',views.job,name="job"),
    path('searchResult/',views.searchResult,name="searchResult"),
    path('employment/',views.addEmployment,name="employment"),
    path('getMessage/<int:appID>/',views.getMessage,name="getMessage"),
    path('sendMessage/',views.sendMessage,name="sendMessage"),
    path('deleteEducation/<int:educID>/',views.deleteEducation,name="deleteEducation"),
    path('deleteWork/<int:workID>/',views.deleteWork,name="deleteWork")

]

GigHubSite/GigHub/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.utils import timezone

import random
# Create your models here.


class Skills(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"

class Institution(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"

class Degrees(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"
    
class Majors(models.Model):
    degree = models.ForeignKey(Degrees, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"
    
class Industry(models.Model):
    name = models.CharField(max_length=255)



class Profile(models.Model):
    userID = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='profiles/', default='profiles/placeholder.png')
    USER_ROLES = [
        ('A','Admin'),
        ('JS','Job Seeker'),
        ('JP','Job Provider')
    ]
    role = models.CharField(max_length=2, choices=USER_ROLES)   
    fName = models.CharField(max_length=255)
    lName = models.CharField(max_length=255)
    mName = models.CharField(max_length=255,null=True)
    suffix = models.CharField(max_length=10,null=True, blank=True)
    contactNo = models.CharField(max_length=13)
    STATUS_CHOICES = [
        ('S','Single'),
        ('M','Married'),
        ('D','Divorced'),
        ('W','Widowed'),
        ('SE','Separated')
    ]
    civilStatus = models.CharField(max_length=20,choices=STATUS_CHOICES, null=True)
    GENDER_CHOICES = [
        ('M','Male'),
        ('F','Female')
    ]
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    sex = models.CharField(max_length=1,choices=GENDER_CHOICES,  null=True)
    birthDate = models.DateField('date_born',  null=True)
    houseNo = models.CharField(max_length=255, null=True)
    baranggay = models.CharField(max_length=255, null=True)
    street = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    province = models.CharField(max_length=255, null=True)
    skills = models.ManyToManyField(Skills)
    verificationLevel = models.IntegerField(default=0)


    def __str__(self) -> str:
        return f"{self.userID.username} : {self.fName} {self.lName}"



class Company(models.Model):
    employerID = models.ManyToManyField(Profile)
    companyName = models.CharField(max_length=255)
    industry = models.ForeignKey(Industry, on_delete=models.DO_NOTHING, null=True)
    empRange = models.CharField(max_length=50, null=True)
    province = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    baranggay = models.CharField(max_length=255, null=True)
    strt = models.CharField(max_length=255, null=True)
    bldgNo = models.CharField(max_length=255, null=True)
    isActive = models.BooleanField(default=True)


    def __str__(self) -> str:
        return self.companyName

class JobPostings(models.Model):
    companyID = models.ForeignKey(Company, on_delete=models.Case)
    jobTitle = models.CharField(max_length=255) #input field
    jobDescription = models.TextField() #text field na malaki
    jobRequirements = models.ManyToManyField(Skills) #multiple input fields na may same names like requirements[] para mareturn sila as array sa backend
    category = models.CharField(max_length=100, null=True)
    scope = models.CharField(max_length=100, null=True)
    timeline = models.CharField(max_length=100, null=True)
    isApproved = models.BooleanField(default=False)
    datePosted = models.DateField(default=timezone.now())
    deadLine = models.DateField(null=True)

    #def setJobRequirements(self, values):
    #    self.jobRequirements = ','.join(map(str,values))

    #def getJobRequirements(self):
    #    if self.jobRequirements:
    #        return self.jobRequirements.split(',')
    #    else:
    #        return []
        
    def setSalary(self, values):
        return ','.join(map(str, values))

    def getSalary(self):
        if self.salaryRange:
            return self.salaryRange.split(',')
        else:
            return []
        
    def __str__(self) -> str:
        return f"{self.companyID.companyName} : {self.jobTitle} - {self.deadLine}"
               
class JobApplication(models.Model):
    applicantID = models.ForeignKey(Profile, on_delete=models.CASCADE)
    jobID = models.ForeignKey(JobPostings, on_delete=models.CASCADE)
    date = models.DateField("application_date", default=timezone.now())
    STATUS_CHOICES = [
        ('applied','Applied'),
        ('in_progress','In Progress'),
        ('cancelled','Cancelled'),
        ('rejected','Rejected'),
        ('hired','Hired')
    ]
    applicationStatus = models.CharField(max_length=30, choices=STATUS_CHOICES, default='Applied')

    
class passwordOTP(models.Model):
    userID = models.ForeignKey(User, on_delete=models.CASCADE)
    isActivated = models.BooleanField(default=False)
    code = models.CharField(max_length=10)
    date = models.DateTimeField(default=datetime.now())
    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.now()
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return f"{self.userID.username}"


class collegeTaken(models.Model):
    userID = models.ForeignKey(Profile, on_delete=models.CASCADE)
    institution = models.ManyToManyField(Institution)
    degree = models.ManyToManyField(Degrees)
    major = models.ManyToManyField(Majors, blank=True)
    award =  models.CharField(max_length=100, blank=True, null=True)
    yearGraduated = models.CharField(max_length=4)

    def __str__(self) -> str:
        institutions = ", ".join([institution.name for institution in self.institution.all()])
        degrees = ", ".join([degree.name for degree in self.degree.all()])
        return f"{self.userID.userID.username} : {institutions} : {degrees} : {self.yearGraduated}"
    

class companyStaff(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    staff = models.ForeignKey(Profile, on_delete=models.CASCADE)
    designation = models.CharField(max_length=255)


    def __str__(self) -> str:
        return f"{self.company.companyName} : {self.designation}"


class Awards(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    awardForm = models.CharField(max_length=255)
    date = models.CharField(max_length=5)


class Certificates(models.Model):
    user = models.ForeignKey(Profile,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    certificateForm = models.CharField(max_length=255)
    date = models.CharField(max_length=5)




class EmploymentHistory(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    companyName = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    date_started = models.DateField()
    date_ended = models.DateField(null=True)
    duties = models.TextField(null=True)

    def setDuties(self, values):
        return ','.join(map(str, values))

    def getDuties(self):
        if self.duties:
            return self.duties.split(',')
        else:
            return []
    
    

class Activities(models.Model):
    viewer = models.ManyToManyField(Profile)
    content = models.CharField(max_length=255)
    dateandtime = models.DateTimeField(auto_now_add=True)

class Room(models.Model):
    jobApp = models.ForeignKey(JobApplication, on_delete=models.CASCADE)


class Message(models.Model):
    date = models.DateTimeField(auto_now_add=True, null=True)
    message = models.ForeignKey(Room, on_delete=models.CASCADE)
    messageContent = models.CharField(max_length=255)
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE)
    senderRole = models.CharField(max_length=50)
    


    
       

GigHubSite/jobSeeker/templates/job.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <link rel="website icon" type="png " href="{{ '/media/site/logo.png' }}" />
  <title>Jobs</title>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
  <script src="https://kit.fontawesome.com/275edc9f9d.js" crossorigin="anonymous" defer></script>

  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
  <script src="{% static 'js/template.js' %}" defer></script>
  <link rel="stylesheet" href="{% static 'css/template.css' %}" />
  <link rel="stylesheet" href="{% static 'css/job.css' %}" />
  <script src="{% static 'js/jobs.js' %}" defer></script>
  <script>
    var token = '{{csrf_token}}'
    var recommended = {{ recommended| safe}};
    var topReco = {{ topRecommended| safe}};
    console.log(recommended)
  </script>
</head>

<body>
  {% include 'partials/template.html' with user=user %}

  <content class="p-4 pb-5">
    <label class="search_jobs d-flex align-items-center py-1 px-2 rounded-2 mb-3">
      <input id="searchInput" type="text" class="pe-2" placeholder="Search by job title" />
      <button class="d-flex align-items-center gap-1 rounded-2 px-2 py-1"
        onclick="searchJob(document.getElementById('searchInput').value)">
        <iconify-icon icon="mingcute:search-line"></iconify-icon>Search
      </button>
    </label>
    <h3 class="fw-bold">Recommended For You</h3>
    <div class="jobs_list mt-4 d-flex flex-column  gap-3" id="topReco_list"></div>

    <h3 class="fw-bold mt-5">
      Discover Your Next Chapter: Browse Jobs Now!"
    </h3>
    <div class="jobs_list mt-4 d-flex flex-column   gap-3" id="jobList">


    </div>
  </content>
  <template id="jobTemplate">
    <div id="jobContainer" class="job_container justify-content-center align-items-center" style="display: flex;">
      <div class="job lh-sm px-4 py-3 rounded-2 shadow-sm d-flex justify-content-between mb-3">
        <div class="job_main">
          <h4 class="job_title fw-bold mb-1" id="title">
            Software Developer
          </h4>
          <div class="job_company" id="company">ByteCraft Solutions</div>
        </div>
        <div class="job_details align-self-center">
          <div class="job_description fw-bold">
            Description:
            <span class="fw-normal" id="description">We are seeking a highly skilled and motivated Software
              Developer to join our dynamic team. The successful candidate
              will be responsible for designing, coding, and modifying
              software applications according to clients' needs. The Software
              Developer will collaborate with cross-functional teams to
              analyze user needs and implement solutions. This role requires a
              strong understanding of software development life cycle and the
              ability to work on multiple projects simultaneously.</span>
          </div>
          <div class="job_category mt-3 fw-bold">
            Job Category:
            <span class="fw-normal">Information Technology</span>
          </div>
          <div class="job_skills fw-bold">
            Skills Needed:
            <span class="fw-normal" id="requirements">Java, Python, C++, or JavaScript, Web Development
              Frameworks</span>
          </div>
          <div class="job_scope fw-bold">
            Scope & Timeline:
            <span class="fw-normal">≥ 6 Months, Intermediate</span>
          </div>
        </div>
        <div class="job_actions d-flex flex-column align-items-end justify-content-between">
          <iconify-icon icon="iconoir:bookmark" class="job_unsaved"></iconify-icon>
          <iconify-icon icon="iconoir:bookmark-solid" class="job_saved"></iconify-icon>
          <div class="view_job fw-bold w-100 text-center py-1 rounded-2" id="view_job">
            MORE
          </div>
        </div>
        <div class="apply_btn fw-bold px-3 py-2 rounded-2 shadow">
          Apply Now
        </div>
      </div>
    </div>
  </template>

  <template id="notopReco">
    <div class="job lh-sm px-4 py-3 rounded-2 shadow-sm d-flex justify-content-between gap-3">
      <center><span>No jobs found matching your given skills</span></center>
    </div>
  </template>

  <template id="noReco">
    <div class="job lh-sm px-4 py-3 rounded-2 shadow-sm d-flex justify-content-between gap-3">
      <center><span>No Jobs Available</span></center>
    </div>
  </template>
</body>
<script>
  if (recommended.length > 0) {
    recommended.forEach((reco) => {
      var template = document.getElementById("jobTemplate");
      var templateContent = template.content.cloneNode(true);

      templateContent.getElementById("title").textContent = reco.title;
      templateContent.getElementById("company").textContent = reco.company;
      templateContent.getElementById("description").textContent = reco.desc;
      templateContent.getElementById("requirements").textContent =
        reco.requirements.join(",");

      templateContent.getElementById('view_job').setAttribute('data-id', reco.id);
      //only for debug purposes
      //templateContent.getElementById('view_job').addEventListener('click', () => {
      //applyJob(reco.id);
      //});
      document.getElementById("jobList").appendChild(templateContent);
    });
  } else {
    var template = document.getElementById("noReco");
    var templateContent = template.content.cloneNode(true);
    document.getElementById("jobList").appendChild(templateContent);
  }

  if (topReco.length > 0) {
    topReco.forEach((reco) => {
      var template = document.getElementById("jobTemplate");
      var templateContent = template.content.cloneNode(true);

      templateContent.getElementById("title").textContent = reco.title;
      templateContent.getElementById("company").textContent = reco.company;
      templateContent.getElementById("description").textContent = reco.desc;
      templateContent.getElementById("requirements").textContent =
        reco.requirements.join(",");
      templateContent.getElementById('view_job').setAttribute('data-id', reco.id);
      document.getElementById("topReco_list").appendChild(templateContent);

    });
  } else {
    var template = document.getElementById("notopReco");
    var templateContent = template.content.cloneNode(true);
    document.getElementById("topReco_list").appendChild(templateContent);
  }

  function applyJob(id) {
    $.ajax({
      url: "{% url 'jobSeeker:job' %}",
      type: "POST",
      data: { csrfmiddlewaretoken: token, id: id },
      success: (data) => {
        Swal.fire({
          text: data.message,
          icon: "success"
        });
      },
      error: (err) => {
        console.log(err.responseText);
      },
    });
  }

  function searchJob(val) {
    let recommended = document.querySelector("#jobList");
    let recommendeds = recommended.querySelectorAll("#jobContainer");

    recommendeds.forEach(reco => {

      if (!reco.querySelector("#title").textContent.includes(val)) {
        reco.style.display = "none";
      } else {
        reco.style.display = "flex"
      }

    });
  }
</script>

</html>

GigHubSite/jobSeeker/templates/searchResult.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="website icon" type="png " href="{{ '/media/site/logo.png' }}" />
    <title>Jobs</title>

    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script
      src="https://kit.fontawesome.com/275edc9f9d.js"
      crossorigin="anonymous"
      defer></script>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script src="{% static 'js/template.js' %}" defer></script>
    <script src="{% static 'js/searchResults.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/template.css' %}" />
    <link rel="stylesheet" href="{% static 'css/search_results.css' %}" />
    <script>
      var token = '{{csrf_token}}'
    </script>
  </head>
  <body>
    {% include 'partials/template.html' with user=user %}

    <content class="p-4 pb-5 d-flex flex-column">
      <div class="message_cont" id="messageCont" >
        <div class="msg d-flex flex-column">
          <div class="close_msg fs-3">
            <iconify-icon icon="zondicons:close-outline"></iconify-icon>
          </div>
          <div class="d-flex flex-column chats" id="chatContaner">
            

            
            
          </div>
          <div class="d-flex align-items-center gap-2">
            
              
            <input type="hidden" id="roomToken" name="roomToken">
            <input
              id="sendMessage"
              type="text"
              placeholder="Enter your message here..."
              class="flex-grow-1 px-2 py-1" />
            
            <button class="d-flex align-items-center justify-content-center" onclick="sendMessage(document.getElementById('sendMessage').value)">
              <iconify-icon icon="mingcute:send-line"></iconify-icon>
            </button>
          </div>
        </div>
      </div>
      <!-- <label
        class="search_jobs d-flex align-items-center py-1 px-2 rounded-2 mb-3 align-self-end">
        <input
          type="text"
          class="pe-2"
          placeholder="Search by Name, Location, Skills, etc.," />
        <button class="d-flex align-items-center gap-1 rounded-2 px-2 py-1">
          <iconify-icon icon="mingcute:search-line"></iconify-icon>Search
        </button>
      </label> -->

      <div class="filter d-flex align-items-center gap-1">
        <div class="d-flex align-items-center gap-1">
          <iconify-icon icon="majesticons:filter" class="fs-5"></iconify-icon>
          <span class="fw-bold">Filter By</span>
        </div>
        <div class="column_filter px-2 py-1 rounded-2" id="jobTitle">
          Job Title
        </div>
        <div class="column_filter px-2 py-1 rounded-2" id="company">
          Company
        </div>
        <!-- <div class="column_filter px-2 py-1 rounded-2" id="date">
          <input type="date" />
        </div> -->
        <div class="column_filter dropdown">
          <div class="ddown d-flex align-items-center rounded-2">
            <input
              type="text"
              id="status"
              class="px-2 py-1"
              readonly="readonly"
              placeholder="Status" />
            <iconify-icon icon="mingcute:down-fill" class="pe-2"></iconify-icon>
          </div>
          <div class="ddown_options position-absolute rounded-3 shadow">
            <div class="ddown_opt px-2 rounded-2 mx-2 my-1">Hired</div>
            <div class="ddown_opt px-2 rounded-2 mx-2 my-1">In Progress</div>
            <div class="ddown_opt px-2 rounded-2 mx-2 my-1">Applied</div>
            <div class="ddown_opt px-2 rounded-2 mx-2 my-1">Rejected</div>
          </div>
        </div>
        <div class="filter_clear px-3 py-1 rounded-2">Clear</div>
      </div>
      <div class="myTable p-3 rounded-2 mt-3">
        <table id="jobTable" class="display" style="width: 100%">
          <thead>
            <tr>
              <th class="py-2 text-center">Job Title</th>
              <th class="py-2 text-center">Company</th>
              <th class="py-2 text-center">Date Applied</th>
              <th class="py-2 text-center">Status</th>
              <th class="py-2 text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for job in jobs %}
            <tr>
              <td data-title="Job Title">{{job.jobID.jobTitle}}</td>
              <td data-title="Company">{{job.jobID.companyID.companyName}} </td>
              <td data-title="Date Applied">{{job.date}}</td>
              <td data-title="Status">{{job.get_applicationStatus_display}}</td>
              <td data-title="Actions">
                
                <iconify-icon icon="solar:eye-broken"  data-id="{{job.id}}" onclick="showMesssages({{job.id}})"></iconify-icon>
                
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>
      </div>
    </content>
    <template id="providerReply">
      <div class="provider px-3 py-2 align-self-start" id="content">
        Hi! Sure thing. You can use jQuery's hide() method. Could you
        share a bit more about your HTML structure and which button
        triggers the action?i
      </div>
      <small class="userdts align-self-start mb-3" id="date"
        >December 12, 2023 11:17am</small
      >
      
    </template>

    <template id="seekerReply">
      <div class="user px-3 py-2 align-self-end" id="content">
        Hey, I'm working on a web project and need some help with jQuery.
        How can I hide an element when a button is clicked?
      </div>
      <small class="userdts align-self-end mb-3" id="date"
        >December 12, 2023 11:16am</small
      >
    </template>
  </body>
  <script>
    function sendMessage(val)
    {
      $.ajax({
        type:"POST",
        url:"/user/sendMessage/",
        data:{"csrfmiddlewaretoken":token,'content':val,'id':document.getElementById('roomToken').value},
        success:(data)=>{
          if(data.status)
          {
            let template = document.getElementById('seekerReply')
            var templateContent = template.content.cloneNode(true);

            templateContent.querySelector('#content').textContent = val
            templateContent.querySelector('#date').textContent = getCurrentDateTime()
            document.querySelector('#chatContaner').appendChild(templateContent)
          }
        },error:(err)=>{
          console.log(err.responseText)
        }
      })
      
    }

    function getCurrentDateTime() {
    const months = [
      "January", "February", "March", "April",
      "May", "June", "July", "August",
      "September", "October", "November", "December"
    ];
  
    const currentDate = new Date();
  
    const month = months[currentDate.getMonth()];
    const day = currentDate.getDate();
    const year = currentDate.getFullYear();
    const hours = currentDate.getHours();
    const minutes = currentDate.getMinutes();
    const period = hours >= 12 ? 'PM' : 'AM';
  
    // Convert 24-hour format to 12-hour format
    const formattedHours = hours % 12 || 12;
  
    const formattedDateTime = `${month} ${day}, ${year} ${formattedHours}:${minutes < 10 ? '0' : ''}${minutes} ${period}`;
  
    return formattedDateTime;
  }



  function showMesssages(id)
  {
    document.querySelector("#messageCont").style.display = "flex"
  $.ajax({
    type:"GET",
    url:`/user/getMessage/${id}/`,
    success:(data)=>{
      
      document.getElementById("chatContaner").innerHTML = ""
      document.getElementById('roomToken').value = id
      data.messages.forEach(message=>{
        
        
        if(message.role == "JP")
        {
          let template = document.getElementById('providerReply')
          var templateContent = template.content.cloneNode(true);

          templateContent.querySelector('#content').textContent = message.content
          templateContent.querySelector('#date').textContent = message.date

          document.querySelector('#chatContaner').appendChild(templateContent)
        }
        else
        {
          let template = document.getElementById('seekerReply')
          var templateContent = template.content.cloneNode(true);

          templateContent.querySelector('#content').textContent = message.content
          templateContent.querySelector('#date').textContent = message.date

          document.querySelector('#chatContaner').appendChild(templateContent)
        }
        
      })
    },error:(err)=>{
      console.log(err.responseText)
    }
  })
  }
  </script>
</html>