GigHubSite/GigHub/urls.py
from django.urls import path
from . import views


app_name = "GigHub"

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login, name="login"),
    path('register/',views.register, name="register"),
    path('privacy_policy/',views.privacy_policy, name="privacy_policy"),
    path('forgot/',views.forgot, name="forgot"),
    path('verify/',views.verify, name="verify"),
    path('changePass/',views.changePass, name="changePass"),
    path('logout/', views.logout, name="logout"),
    path('changeProfile/', views.Profilechange, name="changeProfile"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('addSkills/', views.addSkills, name="addSkills"),
    path('addCollege/',views.addCollege, name="addCollege"),
    path('addCompany/',views.addCompany, name="addCompany"),
    path('addPosting/',views.addJobPosting, name="addJobPosting"),
    path('register_education/', views.register_education, name="register_education"),
    path('register_skills/', views.register_skills, name="register_skills"),
    path('register_moreInfo/', views.register_moreInfo, name="register_moreInfo"),
    path('getMajors/<str:degreeName>/', views.getMajors, name="getMajors"),
    path('disabled/',views.disabled,name="disabled")
]

GigHubSite/GigHubSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GigHub.urls')),
    path('user/',include('jobSeeker.urls')),
    path('provider/',include('jobProvider.urls')),
    path('administrator/',include('gigAdmin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GigHubSite/jobProvider/urls.py
from django.urls import path
from . import views


app_name = "jobProvider"

urlpatterns = [
    path('company/',views.companies, name="companies"),
    path('settings/',views.settings, name="settings"),
    path('getCompany/<int:coID>/',views.getCompany, name="getCompany"),
    path('editCompany/',views.editCompany,name="editCompany"),
    path('jobs/',views.jobPostings,name="jobPostings"),
    path('job/<int:jobID>/',views.jobPosting,name="jobPosting"),
    path('getApplicant/<int:applicantID>/',views.getApplicant,name="getApplicant"),
    path('reply/',views.sendReply,name="sendReply"),
    path('accept/<int:applicantID>/',views.acceptApplication,name="acceptApplication"),
    path('hire/<int:applicantID>/',views.hireApplication,name="acceptApplication"),
    path('reject/<int:applicantID>/',views.rejectApplication,name="acceptApplication"),
    path('dashboard/',views.dashboard,name="dashboard")
]

GigHubSite/jobProvider/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from GigHub.models import Profile, collegeTaken, Activities,Institution, Majors, Degrees, JobPostings, Awards, Certificates, Company, Industry, companyStaff, JobApplication, Skills, EmploymentHistory,Room,Message
from GigHub import utils
from django.contrib.auth.models import User
from datetime import date, datetime
from django.contrib.auth.hashers import check_password
from django.db import models
from django.db.models import Count, Q
# Create your views here.


def companies(request):
    template = 'company.html'
    if request.method == "GET":
        
        profile = Profile.objects.get(userID=request.user)
        companies = Company.objects.filter(employerID=profile)
        companies_data_list = []
        for co in companies:
            company_data = {
                'id':co.id,
                'name':co.companyName,
                'industry':co.industry.name,
                'empRange':co.empRange,
                'location':f"{co.bldgNo} , {co.strt} {co.baranggay} {co.city}, {co.province}"
            }

            companies_data_list.append(company_data)
        return render(request, template, {'pageName':'companies','user':profile, 'companies':companies_data_list})
    else:
        
        profile = Profile.objects.get(userID=request.user)

        coName = request.POST['name']
        coInd = request.POST['industry']
        empRange = request.POST['empRange']
        province = request.POST['province']
        city = request.POST['city']
        brgy = request.POST['baranggay']
        street = request.POST['street']
        bldg = request.POST['bldg']

        industry, created = Industry.objects.get_or_create(name__iexact=coInd)
        if created or not industry.name:
            industry.name = coInd
            industry.save()

        company = Company.objects.create(companyName=coName,empRange=empRange, industry=industry,
                                         province=province,city=city,baranggay=brgy,
                                         strt=street,bldgNo=bldg)
        company.employerID.add(profile)

        
        company.save()

        companyStaff.objects.create(company=company,staff=profile,designation=request.POST['designation'])

        return JsonResponse({'status':True,'message':'Company Added'})

def editCompany(request):
    
        
    coName = request.POST['name']
    coInd = request.POST['industry']
    empRange = request.POST['employees']
    province = request.POST['province']
    city = request.POST['city']
    brgy = request.POST['barangay']
    street = request.POST['street']
    bldg = request.POST['bldg']

    industry, created = Industry.objects.get_or_create(name__iexact=coInd)
    if created or not industry.name:
        industry.name = coInd
        industry.save()

    company = Company.objects.get(id=request.POST['companyID'])

    company.companyName = coName
    company.empRange = empRange
    company.industry = industry
    company.province = province
    company.city = city
    company.baranggay = brgy
    company.strt = street
    company.bldgNo = bldg
    company.save()


    staff = companyStaff.objects.get(company=company,staff=Profile.objects.get(userID=request.user))
    desi = request.POST.get('designation',None)
    if desi is not None:
        staff.designation = request.POST['designation']
        staff.save()

    return redirect('jobProvider:companies')


    

    

def settings(request):
    template = 'providerSettings.html'
    if request.method == "GET":
        
        profile=Profile.objects.get(userID=request.user)
       
        colleges_queryset = collegeTaken.objects.filter(userID=profile)
        awards_queryset = Awards.objects.filter(user=profile)
        college_data_list = []
        certificate_data_list = []
        certificates_queryset = Certificates.objects.filter(user=profile)
        ins = Institution.objects.all()
        deg = Degrees.objects.all()


        awards_data_list = []
        
        for college in colleges_queryset:
            institutions = [institution.name for institution in college.institution.all()]
            degrees = [degree.name for degree in college.degree.all()]
            majors = [major.name for major in college.major.all()]

            college_data = {
                'institutions': institutions,
                'degrees': degrees,
                'majors': majors,
                'award':college.award if college.award is not None else '',
                'yearGraduated': college.yearGraduated,
            }

            college_data_list.append(college_data)

        for award in awards_queryset:

            award_data = {
                'title':award.title,
                'from':award.awardForm,
                'date':award.date
            }

            awards_data_list.append(award_data)

        for certiifcate in certificates_queryset:

            certiifcate_data = {
                'title':certiifcate.title,
                'from':certiifcate.certificateForm,
                'date':certiifcate.date
            }

            certificate_data_list.append(certiifcate_data)


        
        

        bdate = profile.birthDate
        today = date.today()
        age = today.year - bdate.year - ((today.month, today.day) < (bdate.month, bdate.day))
        return render(request, template, {'certis':certificate_data_list,'awards':awards_data_list,'user':profile, 'age':age, 'statuses':profile.STATUS_CHOICES, 'pageName':'profileSettings', 'pagePart': 1, 'colleges':college_data_list, 'degrees':deg,'insitutions':ins})
    elif request.method == "POST":
        
        profile = Profile.objects.get(userID=request.user)
        
        profile.fName = request.POST['fName']
        profile.lName = request.POST['lName']
        profile.mName = request.POST['mName']
        profile.suffix = request.POST['suffix']
        profile.civilStatus = request.POST['status']
        profile.sex = request.POST['sex']
        profile.birthDate = request.POST['birthday']
        profile.baranggay = request.POST['barangay']
        profile.city = request.POST['city']
        profile.province = request.POST['province']
        if request.FILES.get('profileImg') is not None:
            profile.image = request.FILES.get('profileImg')

        profile.save()
        
        profile=Profile.objects.get(userID=request.user)
        certificates_queryset = Certificates.objects.filter(user=profile)
        colleges_queryset = collegeTaken.objects.filter(userID=profile)
        
        awards_queryset = Awards.objects.filter(user=profile)

        certificate_data_list = []
        awards_data_list = []
        ins = Institution.objects.all()
        deg = Degrees.objects.all()

        college_data_list = []
        for college in colleges_queryset:
            institutions = [institution.name for institution in college.institution.all()]
            degrees = [degree.name for degree in college.degree.all()]
            majors = [major.name for major in college.major.all()]

            

            college_data = {
                'institutions': institutions,
                'degrees': degrees,
                'majors': majors,
                'award':college.award if college.award is not None else '',
                'yearGraduated': college.yearGraduated,
            }

            college_data_list.append(college_data)

        for award in awards_queryset:

            award_data = {
                'title':award.title,
                'from':award.awardForm,
                'date':award.date
            }

            awards_data_list.append(award_data)

        for certiifcate in certificates_queryset:

            certiifcate_data = {
                'title':certiifcate.title,
                'from':certiifcate.certificateForm,
                'date':certiifcate.date
            }

            certificate_data_list.append(certiifcate_data)
        
        

        bdate = profile.birthDate
        today = date.today()
        age = today.year - bdate.year - ((today.month, today.day) < (bdate.month, bdate.day))
        return render(request, template, {'certis':certificate_data_list,'awards':awards_data_list,'user':profile, 'age':age, 'statuses':profile.STATUS_CHOICES, 'pageName':'profileSettings', 'prompt':'Profile has been saved', 'pagePart': 1, 'colleges':college_data_list, 'degrees':deg,'insitutions':ins})
    

def getCompany(request, coID):
    company = Company.objects.get(id=coID)
    designation = companyStaff.objects.get(company=company,staff=Profile.objects.get(userID=request.user))

    

    companyData = {
        'designation':designation.designation,
        'name': company.companyName,
        'industry': company.industry.name,
        'empRange': company.empRange,
        'province': company.province,
        'city': company.city,
        'baranggay': company.baranggay,
        'strt': company.strt,
        'bldgNo': company.bldgNo
    }



    return JsonResponse({'status':True,'data':companyData})

def jobPostings(request):
    template = "jobPostings.html"
    if request.method == "GET":
        skillsset = Skills.objects.annotate(profile_count=Count('profile')).order_by('-profile_count')[:5]

        user = Profile.objects.get(userID=request.user)
        companies = Company.objects.filter(employerID=user)
        companies_data_list = []

        for co in companies:

            company_data = {
                'id':co.id,
                'name':co.companyName,
            }

            companies_data_list.append(company_data)

        jobs = JobPostings.objects.filter(companyID__in=companies)

        job_data_list = []

        for job in jobs:
            skills = [skills.name for skills in job.jobRequirements.all()][:3]

            job_data = {
                'id':job.id,
                'title':job.jobTitle,

GigHubSite/jobProvider/templates/partials/navandside.html
<div class="navbar w-auto d-flex align-items-center justify-content-between">
  <div class="leftNavBar w-auto d-flex align-items-center">
      <i class="fa-solid fa-bars" onclick="toggleSidebar(this)"></i>
      
  </div>
  <div class="rightNavbar w-auto h-100 d-flex align-items-center">
      <div class="notificationsContainer">
          <div class="notifContainer">
              <div class="notification">
                  <div class="notif unread">
                      <span class="dot"></span>
                      <div class="notifImg">
                          <img src="" alt="">
                      </div>
                      <div class="notifContent">
                          <span class="notifTitle">My bago</span>
                          <span class="notifBody">dasada</span>
                      </div>
                  </div>
                  <div class="notif">
                      <span class="dot"></span>
                      <div class="notifImg">
                          <img src="" alt="">
                      </div>
                      <div class="notifContent">
                          <span class="notifTitle">My bago</span>
                          <span class="notifBody">dasada</span>
                      </div>
                  </div>
              </div>
          </div>
          
      </div>
      <div class="infoContainer d-flex align-items-center">
          <div class="imgLogin">
              <img src="/media/{{ user.image }}" alt="">
          </div>
          <div class="greetings">
              <span class="greet">Good Day!</span>
              <div class="nameLogin">{{user.fName}} {{user.lName}}</div>
          </div>
      </div>
  </div>
</div>
<div class="sideBar">
  <div class="imgGroupSidebar">
      <img src="{{ '/media/site/logo.png' }}" alt="">
      <img src="{{ '/media/site/logoText.png' }}" alt="" id="hiddenIMG">
  </div>
  <nav>
      <ul>
          <li class="">
              <a href="{% url 'jobProvider:dashboard' %}">
                  <iconify-icon icon="ic:round-dashboard"></iconify-icon>
                  <span class="links">Dashboard</span>
              </a>
          </li>
         
          <li class="">
              <a href="{% url 'jobProvider:settings' %}">
                  <iconify-icon icon="iconamoon:profile-circle-fill"></iconify-icon>
                  <span class="links">Profile Employer</span>
              </a>
          </li>
          
          <li class="">
              <a href="{% url 'jobProvider:companies' %}">
                  <iconify-icon icon="mdi:company"></iconify-icon>
                  <span class="links">Company</span>
              </a>
          </li>
          <li class="">
              <a href="{% url 'jobProvider:jobPostings' %}">
                  <i class="fa-solid fa-user-tie"></i>
                  <span class="links">Job Postings</span>
              </a>
          </li>
          <li class="" onclick="logout()">
              <a href="#">
                  <iconify-icon icon="basil:logout-solid"></iconify-icon>
                  <span class="links">Logout</span>
              </a>
              
          </li>
      </ul>
  </nav>
  <script>
    function logout()
    {
     Swal.fire({
     text: "Are you sure?",
     icon: "question",
     showCancelButton: true,
     confirmButtonText: "Yes",
     }).then((result)=>{
         if(result.isConfirmed)
         {
             window.location.href = "/logout/"
         }
     });
    }
  </script>
</div>

GigHubSite/jobProvider/templates/partials/navandside2.html
<sidebar
  class="shadow d-flex flex-column align-items-center justify-content-between py-3 gap-3"
>
  <div class="logo">
    <img src="{{ '/media/site/logo.png' }}" alt="logo" />
    <img src="{{ '/media/site/logoText.png' }}" />
  </div>

  <div class="d-flex flex-column flex-grow-1 w-100 px-5 justify-content-between">
    <div class="tabs_list d-flex flex-column">
      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 w-100 rounded-2 {% if pageName == 'dashBoard'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobProvider:dashboard' %}`"
      >
        <iconify-icon icon="ic:round-dashboard" style="font-size: 40px; margin-right: 10px;"></iconify-icon>
        <span style="font-size: 20px;">Dashboard</span>
      </div>

      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2 {% if pageName == 'profileSettings'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobProvider:settings'%}`"
      >
        <iconify-icon icon="iconamoon:profile-circle-fill" style="font-size: 40px; margin-right: 10px;"></iconify-icon>
        <span style="font-size: 20px;">Profile</span>
      </div>

      

      <div class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2"
        onclick="window.location.href = `{% url 'jobProvider:companies' %}`">
        <iconify-icon icon="solar:case-bold" style="font-size: 40px; margin-right: 10px;"></iconify-icon>
        <span>Company</span>
      </div>

      <div
        class="tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2 {% if pageName == 'job'%}active{% endif %}"
        onclick="window.location.href = `{% url 'jobProvider:jobPostings'%}`"
      >
        <i class="fa-solid fa-user-tie" style="font-size: 40px; margin-right: 10px;"></i>
        <span style="font-size: 20px;">Job</span>
      </div>

    </div>

    <div onclick="logout()"
      class="logout tabs d-flex align-items-center gap-1 px-3 py-1 rounded-2"
    >
      <iconify-icon icon="basil:logout-solid" style="font-size: 40px; margin-right: 10px;"></iconify-icon>
      <span style="font-size: 20px;">Logout</span>
    </div>
  </div>
</sidebar>
<header class="px-3 d-flex align-items-center gap-2 justify-content-between">
  <div class="left d-flex align-items-center gap-2">
    <iconify-icon icon="ci:hamburger-md" class="burger"></iconify-icon>
  </div>
  <div class="right d-flex align-items-center gap-2">
    
    <div id="shadow" style="height: auto; width: auto;">
      <img
      src="{{ user.image.url }}"
      alt="my_profile"
      class="rounded-circle shadow-sm"
      style="height: 80px;width: 80px;"
    /></div>
    
    <div class="greetings fw-bold lh-sm">
      Good Day!
      <br />
      <span>{{user.fName}} {{user.lName}}</span>
    </div>
  </div>
</header>
<script>
  function logout()
  {
   Swal.fire({
   text: "Are you sure?",
   icon: "question",
   showCancelButton: true,
   confirmButtonText: "Yes",
   }).then((result)=>{
       if(result.isConfirmed)
       {
           window.location.href = "/logout/"
       }
   });
  }
</script>