GigHubSite/GigHub/urls.py
from django.urls import path
from . import views


app_name = "GigHub"

urlpatterns = [
    path('',views.index,name="index"),
    path('login/',views.login, name="login"),
    path('register/',views.register, name="register"),
    path('privacy_policy/',views.privacy_policy, name="privacy_policy"),
    path('forgot/',views.forgot, name="forgot"),
    path('verify/',views.verify, name="verify"),
    path('changePass/',views.changePass, name="changePass"),
    path('logout/', views.logout, name="logout"),
    path('changeProfile/', views.Profilechange, name="changeProfile"),
    path('aboutUs/', views.aboutUs, name="aboutUs"),
    path('addSkills/', views.addSkills, name="addSkills"),
    path('addCollege/',views.addCollege, name="addCollege"),
    path('addCompany/',views.addCompany, name="addCompany"),
    path('addPosting/',views.addJobPosting, name="addJobPosting"),
    path('register_education/', views.register_education, name="register_education"),
    path('register_skills/', views.register_skills, name="register_skills"),
    path('register_moreInfo/', views.register_moreInfo, name="register_moreInfo"),
    path('getMajors/<str:degreeName>/', views.getMajors, name="getMajors"),
    path('disabled/',views.disabled,name="disabled")
]

GigHubSite/GigHubSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('GigHub.urls')),
    path('user/',include('jobSeeker.urls')),
    path('provider/',include('jobProvider.urls')),
    path('administrator/',include('gigAdmin.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GigHubSite/GigHub/views.py
from venv import logger
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.shortcuts import get_object_or_404
from .models import Profile, passwordOTP, Skills,collegeTaken, Institution, Degrees, Majors, Company, JobPostings
from django.test import Client
from .utils import send_email, checkVerification, checkGuest, checkAuth
from django.contrib.auth.models import User
from datetime import datetime
import random
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.db.models import Count

# Create your views here.
def index(request):
    #verifyMiddleware = checkVerification(Profile.objects.get(userID=request.user))
    #if verifyMiddleware != True:
    #    return redirect(f"{verifyMiddleware}")
    
    template = "index.html"
    if request.user.is_authenticated:
        if 'user_profile' in request.session:
            session_arr = request.session['user_profile']
            return render(request, template, context={'session_arr': session_arr})
        else:
            profile = Profile.objects.get(userID=request.user)
            image_url = profile.image.url if profile.image else ''
            birth_date_str = profile.birthDate.strftime('%Y-%m-%d') if profile.birthDate else ''
            userData = request.session['user_profile'] = {
                'user_id' : profile.id,
                'image' : image_url,
                'role' : profile.role,
                'fName' : profile.fName,
                'lName' : profile.lName,
                'mName' : profile.mName,
                'contact' : profile.contactNo,
                'civilStatus' : profile.civilStatus,
                'sex' : profile.sex,
                'active' : profile.is_active,
                'bDay' : birth_date_str,
                'house' : profile.houseNo,
                'street':profile.street,
                'city':profile.city,
                'province':profile.province
            }
            return render(request, template, context={'session_arr': userData})
    else:
        return render(request, template)

def login(request):
    guest = checkGuest(request)
    if guest != True:
        return redirect(f"{guest}")

    template = "login.html"
    if request.method == "GET":
        if(request.user.is_authenticated):
            return redirect('GigHub:index')
        else:
            return render(request, template)
        
    elif request.method == "POST":
        remember_me = request.POST.get('remember', False)
        if request.user.is_authenticated:
            if 'user_profile' in request.session:
                del request.session['user_profile']
            logout(request)
        user = authenticate(request, username=request.POST['email'], password=request.POST['password'])
        if user is not None and user.is_active:
            auth_login(request, user)
            profile = Profile.objects.get(userID=user)
            if profile.is_active is not True:
                return redirect('GigHub:disabled')
            image_url = profile.image.url if profile.image else ''
            birth_date_str = profile.birthDate.strftime('%Y-%m-%d') if profile.birthDate else ''
            userData = request.session['user_profile'] = {
                'user_id' : profile.id,
                'image' : image_url,
                'role' : profile.role,
                'fName' : profile.fName,
                'lName' : profile.lName,
                'mName' : profile.mName,
                'contact' : profile.contactNo,
                'civilStatus' : profile.civilStatus,
                'sex' : profile.sex,
                'active' : profile.is_active,
                'bDay' : birth_date_str,
                'house' : profile.houseNo,
                'street':profile.street,
                'city':profile.city,
                'province':profile.province
            }
           
            if profile.role == "JP":
                return redirect('jobProvider:settings')
            elif profile.role == "JS":
                return redirect('jobSeeker:userSettings')
            else:
                return redirect('gigAdmin:gigAdmin')
        else:
            return render(request, template, context={'errorMsg' : 'Invalid Credentials'})

        
        
        
    
def forgot(request):
    guest = checkGuest(request)
    if guest != True:
        return redirect(f"{guest}")
    
    if request.method == "GET":
        template = "forgotPassword.html"
        return render(request, template)
    elif request.method == "POST":
        email = request.POST['email']
        user = User.objects.filter(username=email).first()
        if user is None:
            return render(request, "forgotPassword.html", {'errorMsg': 'No Email Found' , 'creds':{'email':request.POST['email'],'password':''}})

        if user.is_active:
            otp = random.randint(100000, 999999)
            request.session['passwordOTP'] = {
                'email': email,
                'otp': otp
            }
            password = passwordOTP(userID=user, code=otp)
            password.save()
            send_email('Reset Password', f"Your password otp is {otp}", user.username)
            return redirect('GigHub:verify')
        else:
            template = "forgotPassword.html"
            context = {'errorMsg': "No Email Found"}
            return render(request, template, context)

        

    
def verify(request):
    guest = checkGuest(request)
    if guest != True:
        return redirect(f"{guest}")

    if request.method == "GET":
        template = "verify.html"
        return render(request, template, context={'creds':request.session['passwordOTP']})
    elif request.method == "POST":
        otpArr = request.POST.getlist('otp[]')      
        email = request.POST['email']
        otpString = ''.join(otpArr)
        
        user = User.objects.filter(username=email).first()
        if user is None:
            return render(request, "verify.html", {'errorMSG':'No user found with that email' , 'creds':{'email':request.POST['email'],'password':''}})
        checkotp = passwordOTP.objects.filter(userID=user,isActivated=False,code=otpString)
        if not checkotp.exists():
            return render(request, "verify.html", {'errorMSG':'You inserted the wrong otp', 'creds':{'email':request.POST['email'],'password':''}})
        else:
            otp = passwordOTP.objects.get(userID=user,isActivated=False,code=otpString)
            otp.isActivated = True
            otp.save()
            return redirect('GigHub:changePass')
        
            
        
def changePass(request):
    guest = checkGuest(request)
    if guest != True:
        return redirect(f"{guest}")

    if request.method == "GET":
        template = "newPassword.html"
        return render(request, template, context={'creds':request.session['passwordOTP']})
    if request.method == "POST":
        template = "newPassword.html"
        user = User.objects.get(username=request.POST['email'])
        user.set_password(request.POST['password'])
        user.save()
        user = authenticate(request, username=user.username, password=request.POST['password'])
        if user is not None:
            auth_login(request, user)
            profile = Profile.objects.get(userID=user)
            image_url = profile.image.url if profile.image else ''
            birth_date_str = profile.birthDate.strftime('%Y-%m-%d') if profile.birthDate else ''
            userData = request.session['user_profile'] = {
                'user_id' : profile.id,
                'image' : image_url,
                'role' : profile.role,
                'fName' : profile.fName,
                'lName' : profile.lName,
                'mName' : profile.mName,
                'contact' : profile.contactNo,
                'civilStatus' : profile.civilStatus,
                'sex' : profile.sex,
                'active' : profile.is_active,
                'bDay' : birth_date_str,
                'house' : profile.houseNo,
                'street':profile.street,
                'city':profile.city,
                'province':profile.province
            }
            return redirect('GigHub:index')
        
        
    
def logout(request):
    #send_email('Logout',f"{request.session['user_profile']['fName']} logged out",'delacruzruss12@gmail.com')
    if request.user.is_authenticated:
        if 'user_profile' in request.session:
            del request.session['user_profile']
        auth_logout(request)
    return redirect('GigHub:index')


def Profilechange(request):
    if request.method == "GET":
        user = User.objects.get(id=request.user.id)
        profile = Profile.objects.get(userID=user)
        image_url = profile.image.url if profile.image else ''
        birth_date_str = profile.birthDate.strftime('%Y-%m-%d') if profile.birthDate else ''
        request.session['user_profile'] = {
                'user_id' : profile.id,
                'image' : image_url,
                'role' : profile.role,
                'fName' : profile.fName,
                'lName' : profile.lName,
                'mName' : profile.mName,
                'contact' : profile.contactNo,
                'civilStatus' : profile.civilStatus,
                'sex' : profile.sex,
                'active' : profile.is_active,
                'bDay' : birth_date_str,
                'house' : profile.houseNo,
                'street':profile.street,
                'city':profile.city,
                'province':profile.province
        }
        #return render(request, template, context={'profile':request.session['user_profile']})
        return HttpResponse(request.session['user_profile'])
    elif request.method == "POST":

GigHubSite/GigHub/templates/disabled.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GigHub's Privacy Policy</title>
    <link
      rel="shortcut icon"
      href="{{ '/media/site/website_logo.png' }}"
      type="image/x-icon"
    />
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <style>
        :root {
  --topaz: #fec887;}
        .login-btn {
  background-color: var(--topaz);
  justify-self: end;
  color: var(--black);
  border: solid 3px var(--topaz);
  transition: var(--transition-1);
  cursor: pointer;
}
    </style>

    <link rel="stylesheet" href="{% static 'css/aboutUs.css' %}" />
  </head>

  <body class="d-flex flex-column justify-content-center align-items-center">
    <container
      class="d-flex flex-column justify-content-center align-items-center rounded-4 shadow"
    >
      <img
        src="{{ '/media/site/header_logo.png' }}"
        alt="GigHub logo"
        class="w-25"
      />
      <h4>Where Passion Meets Purpose</h4>

      <h5 class="section fw-bold my-3">BE AWARE!</h5>

      <p class="indent">
        We regret to inform you that your account has been disabled due to a violation of our community guidelines and rules. Our commitment to maintaining a safe and respectful environment for all users requires strict adherence to these guidelines. If you believe this action is a mistake or if you have any concerns, please feel free to reach out to our support team at [GigHub@email.com]. We understand that mistakes can happen, and we are more than willing to investigate any discrepancies to ensure fairness. Thank you for your understanding and cooperation in upholding the integrity of our platform.
      </p>

      <a
        class="login-btn px-4 py-1 rounded-pill fw-bold text-decoration-none fs-5"
        href="{% url 'GigHub:logout' %}"
        class="text-decoration-none"
        >Log out
      </a>

      
    </container>

    <!-- Bootstrap JavaScript Libraries -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

GigHubSite/GigHub/templates/forgotPassword.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Forgot Password | GigHub</title>
    <link
      rel="shortcut icon"
      href="{{ '/media/site/website_logo.png' }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/forgot-password.css' %}" />
  </head>
  <body>
    <header
      class="d-flex align-items-center justify-content-between position-fixed top-0"
    >
      <a href="/" class="d-flex align-items-center">
        <img src="{{ '/media/site/header_logo.png' }}" alt="logo" />
      </a>
      <a href="" class="register-link text-decoration-none fw-bold">
        <span>Not yet registered?</span>
        <span class="sign-up-link">&nbsp;Sign up&nbsp;</span
        ><span>here</span></a
      >
    </header>
    <content class="d-flex flex-column gap-3 align-items-center pt-5">
      <div class="cta fw-bold text-center">
        Unlock Your Potential:&nbsp;
        <span>Log in</span>&nbsp;to Ignite Your Journey!
      </div>
      <form
        action="{% url 'GigHub:forgot' %}"
        class="rounded-4 shadow py-4 px-5 d-flex flex-column align-items-center"
        method="POST"
      >
        {% if errorMsg %}
        <div class="alert alert-danger" style="width: 100%" role="alert">
          {{errorMsg}}
        </div>
        {% endif %} {% csrf_token %}

        <img src="{{ '/media/site/ResetPass.png' }}" />

        <div class="form-cta fw-bold">Trouble Logging In?</div>
        <div class="form-cta-desc text-center w-75 my-3">
          Enter your email and we’ll send you a verification code to reset your
          password
        </div>
        <label
          class="email-input rounded-2 d-flex align-items-center gap-2 px-2 py-1 w-100"
        >
          <iconify-icon icon="ic:outline-email"></iconify-icon>
          <input
            name="email"
            type="email"
            id="email"
            placeholder="Email Address"
            autocomplete="email"
            class="flex-grow-1"
            minlength="1"
          />
        </label>
        <div class="empty empty-email ms-1 w-100">Email address cannot be blank.</div>
        <div
          class="b2sign d-flex align-items-center justify-content-center my-4"
        >
          Back to Sign in?&nbsp;<a
            href="{% url 'GigHub:login'%}"
            class="text-decoration-none fw-bold"
            >Login</a
          >
        </div>
        <div class="d-flex justify-content-center">
          <!-- palitan ko muna button / n -->
          <button
            type="submit"
            class="submit-form text-decoration-none rounded-pill px-4 py-1 fw-bold"
            id="submitBtn"
            >Send</button
          >
        </div>
      </form>
    </content>
    <script src="{% static 'js/forgotPassword-form-validate.js' %}"></script>
  </body>
</html>

GigHubSite/GigHub/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login to GigHub</title>
    <link
      rel="shortcut icon"
      href="{{ '/media/site/website_logo.png' }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
  </head>
  <body>
    <header
      class="d-flex align-items-center justify-content-between position-fixed top-0"
    >
      <a href="/" class="d-flex align-items-center">
        <img src="{{ '/media/site/header_logo.png' }}" alt="logo" />
      </a>
      <a href="{% url 'GigHub:register' %}" class="register-link text-decoration-none fw-bold">
        <span>Not yet registered?</span>
        <span class="sign-up-link">&nbsp;Sign up&nbsp;</span
        ><span>here</span></a
      >
    </header>
    <content class="d-flex flex-column gap-3 align-items-center pt-5">
      <div class="cta fw-bold text-center">
        Unlock Your Potential:&nbsp;
        <span>Log in</span>&nbsp;to Ignite Your Journey!
      </div>
      <form action="{% url 'GigHub:login' %}" method="POST" class="rounded-4 shadow py-4 px-5" id="loginForm">
        {% if errorMsg %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong>{{ errorMsg }}</strong> You should check in on some of those fields below.
        </div>
        {% endif %}
        {% csrf_token %}
        <label for="email" class="fw-bold">Email Address</label>
        <br />
        <input
          autocomplete="off"
          type="email"
          id="email"
          placeholder="Email Address"
          class="rounded-2 px-2 py-1"
          name="email"
        />
        <div class="empty empty-email ms-1">Email address cannot be blank.</div>

        <label for="password" class="fw-bold">Password</label>
        <br />
        <label
          class="pass-input rounded-2 d-flex align-items-center gap-2 px-2 py-1 w-100"
        >
          <input
            autocomplete="off"
            type="password"
            id="password"
            class="flex-grow-1"
            placeholder="Password"
            name="password"
          />
          <iconify-icon
            icon="mdi:eye-off"
            id="password-eye"
            onclick="togglePassword(this,'password-eye2','text')"
          ></iconify-icon>
          <iconify-icon
            icon="heroicons-solid:eye"
            id="password-eye2"
            onclick="togglePassword(this,'password-eye','password')"
            style="display: none;"
          ></iconify-icon>
        </label>
        <div class="empty empty-pass ms-1">Password cannot be blank.</div>
        <div class="d-flex justify-content-between align-items-center gap-1">
          <div class="d-flex align-items-center gap-1">
            <input type="checkbox" name="remember" id="remember-me" />
            <label for="remember-me" class="remember-me-class">
              Remember Me
            </label>
          </div>
          <a href="{% url 'GigHub:forgot' %}" class="forgot-password"
            >Forgot Password?</a
          >
        </div>
        <div class="d-flex justify-content-center mt-4">
          <a class="submit-form text-decoration-none rounded-pill px-4 py-1 fw-bold" onclick="validateLogin()"> Login </a>
        </div>
        
      </form>
    </content>
    <script src="{% static 'js/login-form-validate.js' %}"></script>
  </body>
</html>

GigHubSite/GigHub/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign Up | GigHub</title>
    <link
      rel="shortcut icon"
      href="{{ '/media/site/website_logo.png' }}"
      type="image/x-icon"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/register.css' %}" />
  </head>
  <body>
    <header
      class="d-flex align-items-center justify-content-between position-fixed top-0"
    >
      <a href="{% url 'GigHub:index' %}" class="d-flex align-items-center">
        <img src="{{ '/media/site/header_logo.png' }}" alt="logo" />
      </a>
      <a
        href="{% url 'GigHub:login' %}"
        class="register-link text-decoration-none fw-bold"
      >
        <span>Already registered?</span>
        <span class="sign-up-link">&nbsp;Sign in&nbsp;</span
        ><span>here</span></a
      >
    </header>
    <content class="d-flex flex-column gap-3 align-items-center py-5">
      <div class="cta fw-bold w-75">
        Craft Your&nbsp;<span>Professional</span><br />Story Today!
      </div>
      <form
        id="regForm"
        action="{% url 'GigHub:register' %}"
        class="rounded-4 shadow py-4 px-5 d-flex flex-column align-items-center"
        method="POST"
        enctype="multipart/form-data"
      >
        {% if errorMSG %}
        <div class="alert alert-danger" style="width: 100%" role="alert">
          {{ errorMSG }}
        </div>
        {% endif %} {% csrf_token %}
        <div class="add-profile d-flex flex-column">
          <label for="profile_picture" class="img">
            <img
              src="{{  '/media/site/register_img.png' }}"
              alt="profile_picture"
              class="shadow-lg rounded-circle"
              id="previewImg"
            />
          </label>

          <label for="profile_picture" class="icon">
            <iconify-icon icon="ic:round-plus"></iconify-icon>
          </label>
          <input
            type="file"
            id="profile_picture"
            accept=".jpeg,.png,.jpg,.gif"
            name="picture"
          />
        </div>

        <div class="form_labels col-12 fw-bold">Fullname</div>
        <div class="fullname col-12 d-flex align-items-center flex-wrap">
          <div class="name">
            <input
              type="text"
              placeholder="Last Name"
              autocomplete="name"
              class="rounded-2 px-2 py-1"
              name="lName"
              id="lastname"
            />
            <div class="msg ps-1 lname_msg">Last name cannot be empty.</div>
          </div>
          <div class="name">
            <input
              type="text"
              placeholder="First Name"
              autocomplete="name"
              class="rounded-2 px-2 py-1"
              name="fName"
              id="firstname"
            />
            <div class="msg ps-1 fname_msg">First name cannot be empty.</div>
          </div>
          <div class="name">
            <input
              type="text"
              placeholder="Middle Name"
              autocomplete="name"
              class="rounded-2 px-2 py-1"
              name="mName"
              id="minitial"
            />
            <div class="msg ps-1 minitial_msg">
              Middle initial cannot be empty.
            </div>
          </div>
        </div>

        <div class="row2 d-flex flex-wrap col-12 mt-1">
          <div class="half-col">
            <label for="mobile" class="form_labels fw-bold w-100">
              Mobile Number
            </label>
            <input
              type="number"
              name="mobile"
              id="mobile"
              class="px-2 py-1 rounded-2 w-100"
              placeholder="Mobile Number"
              name="contact"
              autocomplete="tel"
            />
            <div class="msg_2 mnum_msg msg ps-1">
              Mobile number cannot be empty.
            </div>
          </div>
          <div class="half-col">
            <label for="email" class="form_labels fw-bold w-100">
              Email Address
            </label>
            <input
              type="email"
              name="email"
              id="email"
              name="Email"
              class="px-2 py-1 rounded-2 w-100"
              placeholder="Email Address"
              autocomplete="email"
            />
            <div class="msg_2 msg ps-1 email_msg">
              Email address cannot be empty.
            </div>
          </div>
        </div>
        <div class="row2 d-flex flex-wrap col-12 mt-1">
          <div class="half-col">
            <label for="password" class="form_labels fw-bold w-100"
              >Password
            </label>
            <div
              class="pass-input pass px-2 py-1 d-flex align-items-center rounded-2"
            >
              <input
                type="password"
                class="rounded-2 w-100"
                placeholder="Password"
                name="password"
                autocomplete="new-password"
                id="password"
              />
              <iconify-icon icon="fluent:eye-off-16-filled" id="password-eye">
              </iconify-icon>
            </div>
            <div class="msg_2 msg ps-1 pass_msg">Password cannot be empty.</div>
          </div>
          <div class="half-col">
            <label for="cpassword" class="form_labels fw-bold w-100">
              Confirm Password
            </label>
            <div
              class="pass-input cpass px-2 py-1 d-flex align-items-center rounded-2"
            >
              <input
                type="password"
                class="rounded-2 w-100"
                placeholder="Confirm Password"
                autocomplete="new-password"
                id="cpassword"
              />
              <iconify-icon
                icon="fluent:eye-off-16-filled"
                id="cpassword-eye"
              ></iconify-icon>
            </div>
            <div class="msg_2 msg ps-1 cpass_msg">
              Confirm password cannot be empty.
            </div>
          </div>
        </div>

        <div class="fullname col-12 d-flex align-items-center flex-wrap">
          <div class="name">
            <label for="rolePicker" class="form_labels fw-bold w-100">
              Role
            </label>
            <select name="role" id="rolePicker" class="rounded-2 px-2 py-1">
              <option value="" selected disabled>
                PLEASE SELECT AN OPTION
              </option>
              <option value="JP">Job Provider</option>
              <option option value="JS">Job Seeker</option>
            </select>
            <div class="msg_2 msg ps-1 role_msg">Please select your role.</div>
          </div>
          <div class="name">
            <label for="sex" class="form_labels fw-bold w-100"> Gender </label>
            <select name="sex" id="sex" class="rounded-2 px-2 py-1" id="">
              <option value="" selected disabled>
                PLEASE SELECT AN OPTION
              </option>
              <option value="M">Male</option>
              <option option value="F">Female</option>
            </select>
            <div class="msg ps-1 sex_msg">Please choose your sex.</div>
          </div>
          <div class="name">
            <label for="bdate" class="form_labels fw-bold w-100">
              Birthdate
            </label>
            <input
              type="date"
              class="rounded-2 px-2 py-1"
              name="bdate"
              id="bdate"
              onchange="validateBday()"
              id="bdate"
            />
            <div class="msg ps-1 bdate_msg">Birthday cannot be empty.</div>
          </div>
        </div>

        <small class="w-80 my-4 d-flex align-items-center">
          <input type="checkbox" id="iagree" />
          <label for="iagree">
            Yes, I understand and agree to
            <img src="{{ '/media/site/header_logo.png' }}" alt="GigHub" />'s

            <a href="{% url 'GigHub:privacy_policy' %}" target="blank"
              >Terms of Service</a
            >, including the
            <a href="{% url 'GigHub:privacy_policy' %}" target="blank">
              User Agreement</a
            >
            and
            <a href="{% url 'GigHub:privacy_policy' %}" target="blank">
              Privacy Policy</a
            >.</label
          >
        </small>

        <a
          onclick="validate()"
          class="submit-form text-decoration-none rounded-pill px-4 py-1 fw-bold"
          >Register</a
        >
        
        <!-- <a
          class="submit-form text-decoration-none rounded-pill px-4 py-1 fw-bold"
          >Register</a
        > -->
      </form>
    </content>
    <script src="{% static 'js/register-form-validate.js' %}"></script>
    <script src="{% static 'js/toggle-view-register_password.js' %}"></script>
  </body>
</html>